// Code generated by "stringer -type=DXGI_OUTDUPL_POINTER_SHAPE_TYPE,DXGI_ADAPTER_FLAG -output=dxgi_types_string.go"; DO NOT EDIT.

package dxgi

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DXGI_OUTDUPL_POINTER_SHAPE_TYPE_MONOCHROME-1]
	_ = x[DXGI_OUTDUPL_POINTER_SHAPE_TYPE_COLOR-2]
	_ = x[DXGI_OUTDUPL_POINTER_SHAPE_TYPE_MASKED_COLOR-4]
}

const (
	_DXGI_OUTDUPL_POINTER_SHAPE_TYPE_name_0 = "DXGI_OUTDUPL_POINTER_SHAPE_TYPE_MONOCHROMEDXGI_OUTDUPL_POINTER_SHAPE_TYPE_COLOR"
	_DXGI_OUTDUPL_POINTER_SHAPE_TYPE_name_1 = "DXGI_OUTDUPL_POINTER_SHAPE_TYPE_MASKED_COLOR"
)

var (
	_DXGI_OUTDUPL_POINTER_SHAPE_TYPE_index_0 = [...]uint8{0, 42, 79}
)

func (i DXGI_OUTDUPL_POINTER_SHAPE_TYPE) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _DXGI_OUTDUPL_POINTER_SHAPE_TYPE_name_0[_DXGI_OUTDUPL_POINTER_SHAPE_TYPE_index_0[i]:_DXGI_OUTDUPL_POINTER_SHAPE_TYPE_index_0[i+1]]
	case i == 4:
		return _DXGI_OUTDUPL_POINTER_SHAPE_TYPE_name_1
	default:
		return "DXGI_OUTDUPL_POINTER_SHAPE_TYPE(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DXGI_ADAPTER_FLAG_NONE-0]
	_ = x[DXGI_ADAPTER_FLAG_REMOTE-1]
	_ = x[DXGI_ADAPTER_FLAG_SOFTWARE-2]
}

const _DXGI_ADAPTER_FLAG_name = "DXGI_ADAPTER_FLAG_NONEDXGI_ADAPTER_FLAG_REMOTEDXGI_ADAPTER_FLAG_SOFTWARE"

var _DXGI_ADAPTER_FLAG_index = [...]uint8{0, 22, 46, 72}

func (i DXGI_ADAPTER_FLAG) String() string {
	if i >= DXGI_ADAPTER_FLAG(len(_DXGI_ADAPTER_FLAG_index)-1) {
		return "DXGI_ADAPTER_FLAG(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DXGI_ADAPTER_FLAG_name[_DXGI_ADAPTER_FLAG_index[i]:_DXGI_ADAPTER_FLAG_index[i+1]]
}
